project:
  output_base_path: "/mnt/data/anmol/Lightpipe/output/dataset_v3/"
  seed: 10 # A new seed for a new set of results

assets:
  # Asset paths are specific to your machine, so they remain unchanged.
  objects_dir: "/mnt/data/anmol/DecorativeModels/"
  materials_dir: "/mnt/data/anmol/Lightpipe/materials/"
  hdri_dir: "/mnt/data/anmol/Lightpipe/indoor/hdris"

settings:
  num_videos: 50 # Increased number of videos to generate
  frames_per_video: 77 # Increased frames for smoother animations
  resolution:
    width: 1200
    height: 800
  # Camera settings can be expanded if you implement dynamic camera paths
  camera_settings:
    type: "static" # For now, reflects the current main.py implementation
    poi: [0, 0, 1.0] # Point of Interest the camera looks at
    angle_range: [-60, 60] # Vertical angle range for camera
    orbit_radius: 8.0 # Radius for camera orbit around the scene
    camera_height: [1.0, 3.0] # Height of the camera above the ground

randomization:
  # Each light path is now an object with its own parameters for more control.
  path_types:
    - "LEFT_ORBIT"
    - "RIGHT_ORBIT"
    - "FIGURE_EIGHT"
      # You could add more parameters here, like height variation
  orbit_radius_range: [1.0, 1.5] # Range for orbit radius
  height_variation: 0.5
  light_properties:
    intensity_range: [1000, 2000] # Range for light intensity
    color_variation: [0.8, 1.2] # Variation factor for light color
