project:
  output_base_path: "/mnt/venky/ankitd/anmol/new_vace_training/Lightpipe/output/dataset_v0/"
  seed: 10 # A new seed for a new set of results

assets:
  # Asset paths are specific to your machine, so they remain unchanged.
  objects_dir: "/mnt/venky/ankitd/anmol/new_vace_training/Lightpipe/assets/DecorativeModels"
  materials_dir: "/mnt/venky/ankitd/anmol/new_vace_training/Lightpipe/assets/materials"
  hdri_dir: "/mnt/venky/ankitd/anmol/new_vace_training/Lightpipe/assets/indoor/hdris"

settings:
  num_videos: 80 # Increased number of videos to generate
  frames_per_video: 77 # Increased frames for smoother animations
  enable_depth: false
  resolution:
    width: 900
    height: 600
  # Train/Validation split configuration
  dataset_split:
    train_ratio: 0.8 # 80% for training, 20% for validation
    ensure_disjoint_assets: true # Ensure objects/HDRIs don't overlap between train/val
  # Camera settings can be expanded if you implement dynamic camera paths
  camera_settings:
    type: "static" # For now, reflects the current main.py implementation
    poi: [0, 0, 1.0] # Point of Interest the camera looks at
    angle_range: [-60, 60] # Vertical angle range for camera
    orbit_radius: 8.0 # Radius for camera orbit around the scene
    camera_height: [1.0, 3.0] # Height of the camera above the ground
  light:
    type: "point" # Type of light source
    visible: true # Whether the light is visible in the scene
randomization:
  # Each light path is now an object with its own parameters for more control.
  path_types:
    - "LEFT_ORBIT"
    - "RIGHT_ORBIT"
    - "FIGURE_EIGHT"
      # You could add more parameters here, like height variation
  orbit_radius_range: [1.0, 1.5] # Range for orbit radius
  height_variation: 0.5
  light_properties:
    intensity_range: [200, 800] # Range for light intensity
    color_variation: [0.8, 1.2] # Variation factor for light color
